name: h_m
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.9
  sizer: ^2.0.15
  flutter_svg_provider: ^1.0.3
  dropdown_formfield: ^0.1.4
  easy_localization: ^3.0.0
  flutter_phoenix: ^1.0.0
  flutter_conditional_rendering: ^2.0.0
  flutter_svg: ^1.1.1+1
  flutter_launcher_icons: ^0.9.3
  flutter_screenutil: ^5.5.3+2

  intl_phone_number_input: ^0.7.0+2
  carousel_slider: ^4.0.0
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^2.2.1
  google_maps_flutter: ^2.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/store2.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/

  #   - family: Trajan Pro
  fonts:
    - family: Medium
      fonts:
        - asset: assets/font/Montserrat-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/font/Montserrat-SemiBold.ttf
    - family: Italianno
      fonts:
        - asset: assets/font/Italianno-Regular.otf
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
